/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;


import Negocio.Datos;
import Negocio.Utilidades;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cóndor 2013
 */
public class frmBuscarProyectoJefeSubdivision extends javax.swing.JDialog {

    private DefaultTableModel miTabla;
    private Datos misDatos;
    private String respuesta = "";


    public void setDatos(Datos misDatos) {
        this.misDatos = misDatos;

    }

    public String getRespuesta() {
  return respuesta;

   }
      
    /**
     * Creates new form frmBuscarProyecto
     */
    public frmBuscarProyectoJefeSubdivision(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCriterio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoProyecto = new javax.swing.JTextField();
        txtNombreProyecto = new javax.swing.JTextField();
        lblNombrePro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proyectos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Criterio de Busqueda:");

        txtCriterio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCriterio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCriterioKeyTyped(evt);
            }
        });

        tblTabla.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblTablaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblTabla);

        btnAceptar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accept.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disconnect.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Codigo Proyecto:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        txtCodigoProyecto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCodigoProyecto.setEnabled(false);
        txtCodigoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProyectoActionPerformed(evt);
            }
        });

        txtNombreProyecto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNombreProyecto.setEnabled(false);

        lblNombrePro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombrePro.setText("Proyecto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCriterio))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))))
                    .addComponent(lblNombrePro))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombrePro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obtenerCamposBuscar() {

        int row = tblTabla.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione Fila");
            return;
        } 
        else {

            String codigo_p = tblTabla.getValueAt(row, 0).toString();
            txtCodigoProyecto.setText(codigo_p);
            
            String nombre_p = tblTabla.getValueAt(row, 1).toString();
            txtNombreProyecto.setText(nombre_p);
                     

        }

    }
    
    
    
     private void buscarProyecto(){
              
              String sql = "SELECT * FROM proyecto CROSS JOIN persona, escalafon, grado "
                      + "WHERE persona.idpersona = proyecto.idpersona "
                      + "AND persona.idescalafon = escalafon.idescalafon "
                      + "AND persona.idgrado = grado.idgrado "
                      + "AND codigo_pro = '"+txtCodigoProyecto.getText()+"' ";
              
              ResultSet a = misDatos.getConsulta(sql);
         try {
             while (a.next()){
        
//
                 frmJefeSubdivision.txtCodigoPro.setText(a.getString("codigo_pro"));
                 frmJefeSubdivision.txtNombrePro.setText(a.getString("nombre_pro"));
                 frmJefeSubdivision.dchFechaInicio.setDate(a.getDate("inicio_pro"));
                 frmJefeSubdivision.dchFechaPlazo.setDate(a.getDate("plazo_pro"));
                 frmJefeSubdivision.cmbAvance.setSelectedItem(a.getString("avance_pro"));
                 frmJefeSubdivision.cmbEstado.setSelectedItem(a.getString("estado_pro"));
                 frmJefeSubdivision.cmbPrioridad.setSelectedItem(a.getString("prioridad_pro"));
                 frmJefeSubdivision.cmbMaterialAereo.setSelectedItem(a.getString("material_pro"));
                 frmJefeSubdivision.cmbEncargado.setSelectedIndex(a.getInt("encargado_pro"));
                 frmJefeSubdivision.txaDescripcion.setText(a.getString("descripcion_pro"));
                 
                 
                 
             
                 frmJefeSubdivision.btnModificarProyecto.setEnabled(true);
                 frmJefeSubdivision.btnGuardarProyecto.setEnabled(false);
                 frmJefeSubdivision.deshabilitarComposNuevo();
                 this.dispose();

             }
         } catch (SQLException ex) {
             Logger.getLogger(frmBuscarProyectoJefeSubdivision.class.getName()).log(Level.SEVERE, null, ex);
         }
              
          }
         
    
        private void llenarTabla() {

        String Titulos[] = {"Codigo Proyecto", "Nombre Proyecto", "Inicio","Plazo","Avance","Estado","Material"};
        String registro[] = new String[7];
        miTabla = new DefaultTableModel(null, Titulos);

           String sql = "SELECT * FROM proyecto CROSS JOIN persona, escalafon, grado "
                      + "WHERE persona.idpersona = proyecto.idpersona "
                      + "AND persona.idescalafon = escalafon.idescalafon "
                      + "AND persona.idgrado = grado.idgrado "
                      + "ORDER BY idproyecto desc ";
                                
        
        ResultSet rs = misDatos.getConsulta(sql);
        try {
            while (rs.next()) {

                registro[0] = rs.getString("codigo_pro");
                registro[1] = rs.getString("nombre_pro");
                registro[2] = Utilidades.formatDate2(rs.getDate("inicio_pro"));
                registro[3] = Utilidades.formatDate2(rs.getDate("plazo_pro"));
                registro[4] = rs.getString("avance_pro");
                registro[5] = rs.getString("estado_pro");
                registro[6] = rs.getString("material_pro");

                miTabla.addRow(registro);
            }
            tblTabla.setModel(miTabla);

        } catch (SQLException ex) {
            Logger.getLogger(frmBuscarProyectoJefeSubdivision.class.getName()).log(Level.SEVERE, null, ex);

        }

    }
        
       
        
          private void llenarTablaCriterioBusqueda() {

       String Titulos[] = {"Codigo Proyecto", "Nombre Proyecto", "Inicio","Plazo","Avance","Estado","Material"};
        String registro[] = new String[7];
        miTabla = new DefaultTableModel(null, Titulos);

              String sql = "SELECT * FROM proyecto CROSS JOIN persona, escalafon, grado "
                      + "WHERE persona.idpersona = proyecto.idpersona "
                      + "AND persona.idescalafon = escalafon.idescalafon "
                      + "AND persona.idgrado = grado.idgrado "
                      + "AND CONCAT(codigo_pro,nombre_pro, inicio_pro, plazo_pro, avance_pro, estado_pro,material_pro) "
                      + "LIKE '%" + txtCriterio.getText() + "%' ORDER BY codigo_pro ASC ";
       
        
        ResultSet rs = misDatos.getConsulta(sql);
        try {
            while (rs.next()) {

                registro[0] = rs.getString("codigo_pro");
                registro[1] = rs.getString("nombre_pro");
                registro[2] = Utilidades.formatDate2(rs.getDate("inicio_pro"));
                registro[3] = Utilidades.formatDate2(rs.getDate("plazo_pro"));
                registro[4] = rs.getString("avance_pro");
                registro[5] = rs.getString("estado_pro");
                registro[6] = rs.getString("material_pro");

                miTabla.addRow(registro);
                
            }
            tblTabla.setModel(miTabla);

        } catch (SQLException ex) {
            Logger.getLogger(frmBuscarProyectoJefeSubdivision.class.getName()).log(Level.SEVERE, null, ex);

        }


    }
     
          
         
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        txtCriterio.requestFocusInWindow();
      llenarTabla();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        obtenerCamposBuscar();
        buscarProyecto();
       
        

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        respuesta = "";
        dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCriterioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCriterioKeyTyped

                
llenarTablaCriterioBusqueda();
        
                
    }//GEN-LAST:event_txtCriterioKeyTyped

    private void txtCodigoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProyectoActionPerformed

    private void tblTablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaMousePressed

        obtenerCamposBuscar();
        
    }//GEN-LAST:event_tblTablaMousePressed

    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBuscarProyectoJefeSubdivision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBuscarProyectoJefeSubdivision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBuscarProyectoJefeSubdivision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBuscarProyectoJefeSubdivision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmBuscarProyectoJefeSubdivision dialog = new frmBuscarProyectoJefeSubdivision(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNombrePro;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtCodigoProyecto;
    private javax.swing.JTextField txtCriterio;
    private javax.swing.JTextField txtNombreProyecto;
    // End of variables declaration//GEN-END:variables
}
