/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;


import Negocio.Datos;
import Negocio.Utilidades;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cóndor 2013
 */
public class frmBuscarDocumentacionEncargadoProyecto extends javax.swing.JDialog {

    private DefaultTableModel miTabla;
    private Datos misDatos;
    private String respuesta = "";


    public void setDatos(Datos misDatos) {
        this.misDatos = misDatos;

    }

    public String getRespuesta() {
  return respuesta;

   }
    
     public String codigo_pro;

    public void setCodigo_pro(String codigo_pro) {
        this.codigo_pro = codigo_pro;
    }
    
    
    public String nombreProyecto;

    public void setNombreProyecto(String nombreProyecto) {
        this.nombreProyecto = nombreProyecto;
    }

    
    
      
    /**
     * Creates new form frmBuscarProyecto
     */
    public frmBuscarDocumentacionEncargadoProyecto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCriterio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroDocumento = new javax.swing.JTextField();
        lblNombrePro = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaObjetivo = new javax.swing.JTextArea();
        lblNombrePro1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Documentos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Criterio de Busqueda:");

        txtCriterio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCriterio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCriterioKeyTyped(evt);
            }
        });

        tblTabla.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblTablaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblTabla);

        btnAceptar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accept.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disconnect.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nº Documento:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Objetivo:");

        txtNumeroDocumento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNumeroDocumento.setEnabled(false);
        txtNumeroDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDocumentoActionPerformed(evt);
            }
        });

        lblNombrePro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombrePro.setText("Proyecto:");

        txaObjetivo.setColumns(20);
        txaObjetivo.setRows(5);
        txaObjetivo.setEnabled(false);
        jScrollPane3.setViewportView(txaObjetivo);

        lblNombrePro1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombrePro1.setText("Proyecto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lblNombrePro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addComponent(jScrollPane2)))
                    .addComponent(lblNombrePro)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePro)
                    .addComponent(lblNombrePro1))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 244, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obtenerCamposBuscar() {

        int row = tblTabla.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione Fila");
            return;
        } 
        else {

            String codigo_p = tblTabla.getValueAt(row, 0).toString();
            txtNumeroDocumento.setText(codigo_p);
            
            String nombre_p = tblTabla.getValueAt(row, 1).toString();
            txaObjetivo.setText(nombre_p);
                     

        }

    }
    
    
    
     private void buscarDocumento(){
              
              String sql = "SELECT * FROM documento CROSS JOIN proyecto "
                      + "WHERE documento.idproyecto = proyecto.idproyecto "
                   
                      + "AND numero_doc = '"+txtNumeroDocumento.getText()+"' ";
              
              ResultSet a = misDatos.getConsulta(sql);
         try {
             while (a.next()){
        
//
                 frmDocumentoEncargadoProyecto.txtCodigoPro.setText(a.getString("codigo_pro"));
                 frmDocumentoEncargadoProyecto.txtNombrePro.setText(a.getString("nombre_pro"));
                 frmDocumentoEncargadoProyecto.txtNumeroDoc.setText(a.getString("numero_doc"));
                 frmDocumentoEncargadoProyecto.dchFechaDoc.setDate(a.getDate("fecha_doc"));
                 frmDocumentoEncargadoProyecto.txtPlazoDoc.setText(a.getString("plazo"));
                 frmDocumentoEncargadoProyecto.txtRuta.setText(a.getString("ruta_doc"));
                 frmDocumentoEncargadoProyecto.txaObjetivo.setText(a.getString("objetivo_doc"));
                 
                 
                 
                 
             
                 frmDocumentoEncargadoProyecto.btnModificar.setEnabled(true);
                 frmDocumentoEncargadoProyecto.btnGuardar.setEnabled(false);
                 frmDocumentoEncargadoProyecto.desHabilitarCampos();
                 this.dispose();

             }
         } catch (SQLException ex) {
             Logger.getLogger(frmBuscarDocumentacionEncargadoProyecto.class.getName()).log(Level.SEVERE, null, ex);
         }
              
          }
         
    
        private void llenarTabla() {

        String Titulos[] = {"Nº Documento", "Objetivo", "Fecha","Plazo","Ruta"};
        String registro[] = new String[5];
        miTabla = new DefaultTableModel(null, Titulos);

          String sql = "SELECT * FROM documento CROSS JOIN proyecto "
                      + "WHERE documento.idproyecto = proyecto.idproyecto "
                   + "and codigo_pro = '"+codigo_pro+"' "
                      + "ORDER BY numero_doc ASC ";
                                
        
        ResultSet rs = misDatos.getConsulta(sql);
        try {
            while (rs.next()) {

                registro[0] = rs.getString("numero_doc");
                registro[1] = rs.getString("objetivo_doc");
                registro[2] = Utilidades.formatDate2(rs.getDate("fecha_doc"));
                registro[3] = rs.getString("plazo");
                registro[4] = rs.getString("ruta_doc");
              

                miTabla.addRow(registro);
            }
            tblTabla.setModel(miTabla);

        } catch (SQLException ex) {
            Logger.getLogger(frmBuscarDocumentacionEncargadoProyecto.class.getName()).log(Level.SEVERE, null, ex);

        }

    }
        
       
        
          private void llenarTablaCriterioBusqueda() {

        String Titulos[] = {"Nº Documento", "Objetivo", "Fecha","Plazo","Ruta"};
        String registro[] = new String[5];
        miTabla = new DefaultTableModel(null, Titulos);

              String sql = "SELECT numero_doc,fecha_doc, plazo, objetivo_doc, ruta_doc, "
                      + "documento.idproyecto, codigo_pro "
                      + "FROM documento "
                      + "INNER JOIN proyecto ON proyecto.idproyecto = documento.idproyecto "
                      + "where codigo_pro = '"+codigo_pro+"' "
                      + "and CONCAT(numero_doc,fecha_doc, plazo, objetivo_doc) like '%"+txtCriterio.getText()+"%' "
                      + "ORDER BY numero_doc ASC ";

        
        ResultSet rs = misDatos.getConsulta(sql);
        try {
            while (rs.next()) {

                registro[0] = rs.getString("numero_doc");
                registro[1] = rs.getString("objetivo_doc");
                registro[2] = Utilidades.formatDate2(rs.getDate("fecha_doc"));
                registro[3] = rs.getString("plazo");
                registro[4] = rs.getString("ruta_doc");

                miTabla.addRow(registro);
                
            }
            tblTabla.setModel(miTabla);

        } catch (SQLException ex) {
            Logger.getLogger(frmBuscarDocumentacionEncargadoProyecto.class.getName()).log(Level.SEVERE, null, ex);

        }


    }
     
          
         
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        txtCriterio.requestFocusInWindow();
        lblNombrePro.setText(nombreProyecto);
      llenarTabla();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        obtenerCamposBuscar();
        buscarDocumento();
       frmDocumentoEncargadoProyecto.btnModificar.setEnabled(true);
        

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        respuesta = "";
        dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCriterioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCriterioKeyTyped

                
llenarTablaCriterioBusqueda();
        
                
    }//GEN-LAST:event_txtCriterioKeyTyped

    private void txtNumeroDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDocumentoActionPerformed

    private void tblTablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaMousePressed

        obtenerCamposBuscar();
        
    }//GEN-LAST:event_tblTablaMousePressed

    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBuscarDocumentacionEncargadoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBuscarDocumentacionEncargadoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBuscarDocumentacionEncargadoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBuscarDocumentacionEncargadoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmBuscarDocumentacionEncargadoProyecto dialog = new frmBuscarDocumentacionEncargadoProyecto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNombrePro;
    private javax.swing.JLabel lblNombrePro1;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextArea txaObjetivo;
    private javax.swing.JTextField txtCriterio;
    private javax.swing.JTextField txtNumeroDocumento;
    // End of variables declaration//GEN-END:variables
}
