/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;


import Datos.Proyecto;
import Negocio.Datos;
import Negocio.Opcion;
import Negocio.Utilidades;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author proyectos33
 */
public class frmJefeSubdivision extends javax.swing.JInternalFrame {

    private Datos misDatos; //Variable que almacena el objeto Datos
    private boolean nuevo = false;
    private int IDPERSONA;
    private int anioNumero = 0;
    

    public void setDatos(Datos misDatos) {
        this.misDatos = misDatos;

    }
    
     private void centrarVentana(){
    
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = getSize();
        
        setLocation((pantalla.width - ventana.width)/2, 0);
    
    }
    
        
    public frmJefeSubdivision() {
        initComponents();
        centrarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnNuevoProyecto = new javax.swing.JButton();
        btnModificarProyecto = new javax.swing.JButton();
        btnBuscarProyecto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        cmbEncargado = new javax.swing.JComboBox();
        cmbMaterialAereo = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cmbPrioridad = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbAvance = new javax.swing.JComboBox();
        dchFechaInicio = new com.toedter.calendar.JDateChooser();
        txtNombrePro = new javax.swing.JTextField();
        dchFechaPlazo = new com.toedter.calendar.JDateChooser();
        txtDescripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        cmbEstado = new javax.swing.JComboBox();
        txtDescripcion1 = new javax.swing.JLabel();
        txtCodigoPro = new javax.swing.JTextField();
        btnGuardarProyecto = new javax.swing.JButton();
        lblPersona = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Jefe Subdivisión");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnNuevoProyecto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNuevoProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        btnNuevoProyecto.setText("Nuevo");
        btnNuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProyectoActionPerformed(evt);
            }
        });

        btnModificarProyecto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnModificarProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnModificarProyecto.setText("Modificar");
        btnModificarProyecto.setEnabled(false);
        btnModificarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProyectoActionPerformed(evt);
            }
        });

        btnBuscarProyecto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuscarProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscarProyecto.setText("Buscar");
        btnBuscarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProyectoActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proyecto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Encargado:");

        cmbEncargado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbEncargado.setEnabled(false);

        cmbMaterialAereo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbMaterialAereo.setMaximumRowCount(25);
        cmbMaterialAereo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Material Aereo", "Combate - F16 B50", "Combate - F16 MLU", "Combate - F5 Tigre III", "Combate - A-29 Tucano", "Combate - A-36 Halcon", "Helicoptero - Bell 206", "Helicoptero - Bell 412", "Helicoptero - UH-1H", "Helicoptero - UH-60", "Transporte - C130", "Transporte - Casa 212", "Transporte - Twin Otter", "Transporte - KC 135", "Transporte - B737", "Transporte - B767", "Transporte - B707 Condor", "Transporte - G-IV Gulf Stream", "Instruccion - T-35 Pillan", "Instruccion - CJ-1", "Acrobacia - Extra 300", "Varios" }));
        cmbMaterialAereo.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Material Aereo:");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("Prioridad:");

        cmbPrioridad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbPrioridad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Prioridad", "Alta", "Media", "Baja", "Urgente" }));
        cmbPrioridad.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Estado:");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setText("Inicio:");

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setText("Nombre:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Plazo:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Porcentaje:");

        cmbAvance.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbAvance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Porcentaje de Avance", "0 %", "5 %", "10 %", "15 %", "20 %", "25 %", "30 %", "35 %", "40 %", "45 %", "50 %", "55 %", "60 %", "65 %", "70 %", "75 %", "80 %", "85 %", "90 %", "95 %", "100 %" }));
        cmbAvance.setEnabled(false);

        dchFechaInicio.setEnabled(false);

        txtNombrePro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNombrePro.setEnabled(false);
        txtNombrePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProActionPerformed(evt);
            }
        });

        dchFechaPlazo.setEnabled(false);

        txtDescripcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDescripcion.setText("Descripción:");

        txaDescripcion.setColumns(20);
        txaDescripcion.setRows(5);
        txaDescripcion.setEnabled(false);
        jScrollPane2.setViewportView(txaDescripcion);

        cmbEstado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Estado", "Inicial", "En Estudio", "Termino Postpuesto", "Detenido", "En curso" }));
        cmbEstado.setEnabled(false);

        txtDescripcion1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDescripcion1.setText("Código:");

        txtCodigoPro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCodigoPro.setEnabled(false);
        txtCodigoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDescripcion1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel8)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dchFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dchFechaPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombrePro)
                            .addComponent(cmbMaterialAereo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPrioridad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAvance, 0, 291, Short.MAX_VALUE)
                            .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigoPro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescripcion)
                            .addComponent(jLabel19))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbEncargado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescripcion1)
                            .addComponent(txtCodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(dchFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(dchFechaPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cmbPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cmbMaterialAereo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardarProyecto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardarProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btnGuardarProyecto.setText("Guardar");
        btnGuardarProyecto.setEnabled(false);
        btnGuardarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProyectoActionPerformed(evt);
            }
        });

        lblPersona.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPersona.setForeground(new java.awt.Color(51, 51, 255));
        lblPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user_business.png"))); // NOI18N
        lblPersona.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPersona)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevoProyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarProyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarProyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarProyecto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoProyecto)
                    .addComponent(btnModificarProyecto)
                    .addComponent(btnBuscarProyecto)
                    .addComponent(btnGuardarProyecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPersona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("Proyecto");

        jMenuItem1.setText("Nuevo");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Eliminar");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reportes");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      private void obtenerSesion(){
          try {
              String sql = "SELECT persona.idpersona, nombre_gra, nombre_esc, nombre_per, apellido_per "
                      + "FROM persona INNER JOIN grado ON grado.idgrado = persona.idgrado "
                      + "INNER JOIN escalafon ON escalafon.idescalafon = persona.idescalafon "
                      + "INNER JOIN usuario ON usuario.idPersona = persona.idpersona "
                      + "WHERE nombre_usu = '"+frmPrincipal.usuario+"' ";
              
              ResultSet a = misDatos.getConsulta(sql);
              while (a.next()){
                  String usuarioLog = a.getString("nombre_gra")+' '+a.getString("nombre_esc")+' '+a.getString("nombre_per")+' '+a.getString("apellido_per") ;
                  lblPersona.setText(usuarioLog);
                  IDPERSONA = a.getInt("persona.idpersona");
//                  JOptionPane.showMessageDialog(rootPane, "ID Persona = "+IDPERSONA);
                  
              }
          } catch (SQLException ex) {
              Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
          }
        
        
        
    }
    
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        obtenerSesion();
        obtenerAnioActual();
               
         Opcion opc = new Opcion("Na", "Seleccione Encargado");
                 cmbEncargado.addItem(opc);
                 ResultSet rsPro = misDatos.getEncargado();
                 {
                     try {
                         while (rsPro.next()) {
//                             opc = new Opcion(rsPro.getString("idProyecto"),
//                                        rsPro.getString("idProyecto")+" "+rsPro.getString("codigoBipFach"));
                             
                              opc = new Opcion(rsPro.getString("persona.idPersona"),
                                        rsPro.getString("encargado"));
                             
                                cmbEncargado.addItem(opc);
                            }
                     } catch (SQLException ex) {
                         Logger.getLogger(frmJefeSubdivision.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    }
                 
        
    }//GEN-LAST:event_formInternalFrameOpened

     
    
    
    
    private void btnNuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProyectoActionPerformed

        obtenerCodigoProyecto();
        txtNombrePro.requestFocusInWindow();
        limpiarCampos();
        nuevo = true;
        habilitarComposNuevo();
        
      
        
        
        
    }//GEN-LAST:event_btnNuevoProyectoActionPerformed

    private void obtenerAnioActual(){
        
          //ObtenerFechaParaIngresoDeCodigoDeProyecto
        Date anioPRO = new Date();
        Utilidades.formatDate2(anioPRO);
        anioNumero = anioPRO.getYear();
//        JOptionPane.showMessageDialog(rootPane,  anioNumero);
        
    }
    
    
    private void obtenerCodigoProyecto(){
        try {          
            
            //obtenerNumeroAuto
            String sql = "SELECT COUNT(codigo_pro) + 1 as 'Num' FROM proyecto where anio_pro =  '"+anioNumero+"' ";
            ResultSet a = misDatos.getConsulta(sql);

            if (a.next()) {
                
                    String codigo = String.valueOf(a.getInt("Num"));
                                       
//                    JOptionPane.showMessageDialog(rootPane, codigo);
                    txtCodigoPro.setText(codigo+"/"+anioNumero);
                
            }   
                     
            
        } catch (SQLException ex) {
            Logger.getLogger(frmJefeSubdivision.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    private void btnGuardarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProyectoActionPerformed

        
        if(txtNombrePro.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Ingrese Nombre del Proyecto");
            txtNombrePro.requestFocusInWindow();
            return;
        }

           
            if(dchFechaInicio.getDate()==null){
            JOptionPane.showMessageDialog(rootPane, "Seleccione Fecha Inicio");
            dchFechaInicio.requestFocusInWindow();
            return;
        }
            
             if(dchFechaPlazo.getDate()==null){
            JOptionPane.showMessageDialog(rootPane, "Seleccione Fecha Plazo");
            dchFechaPlazo.requestFocusInWindow();
            return;
        }
        
        
         if(cmbAvance.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Seleccione Porcentaje");
            cmbAvance.requestFocusInWindow();
            return;
        }
         if(cmbEstado.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Seleccione Estado");
            cmbEstado.requestFocusInWindow();
            return;
        }
         
         
          if(cmbPrioridad.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Seleccione Origen del Contrato");
            cmbPrioridad.requestFocusInWindow();
            return;
        }
          if(cmbMaterialAereo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Seleccione Idioma del Contrato");
            cmbMaterialAereo.requestFocusInWindow();
            return;
        }
          
            if(txaDescripcion.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Ingrese Descripción del Proyecto");
            txaDescripcion.requestFocusInWindow();
            return;
        }
          
           if(cmbEncargado.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Seleccione Encargado");
            cmbEncargado.requestFocusInWindow();
            return;
        }
           
       
   
    String codigo_pro = txtCodigoPro.getText().trim();
    int anio_pro = anioNumero;
    String nombre_pro = txtNombrePro.getText().trim();
    Date fechaInicio = dchFechaInicio.getDate();
    Date fechaPlazo = dchFechaPlazo.getDate();
    String avance_pro = cmbAvance.getSelectedItem().toString();
    String estado_pro = cmbEstado.getSelectedItem().toString();
    String prioridad_pro = cmbPrioridad.getSelectedItem().toString();
    String materialAereo_pro = cmbMaterialAereo.getSelectedItem().toString();
    int encargado = cmbEncargado.getSelectedIndex();
    String nombreEncargado_pro = cmbEncargado.getSelectedItem().toString();
    String descripcion_pro = txaDescripcion.getText().trim();
           
    int idpersona_con = IDPERSONA;    
  
        if (nuevo) {

            obtenerCodigoProyecto();
            codigo_pro = txtCodigoPro.getText().trim();

            if (misDatos.existeProyecto(txtCodigoPro.getText())) {

                JOptionPane.showMessageDialog(null, "El Proyecto Ya Existe", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

        }

        Proyecto miProyecto = new Proyecto(codigo_pro, anio_pro, nombre_pro, fechaInicio, fechaPlazo,
                avance_pro, estado_pro, prioridad_pro, materialAereo_pro,
                encargado, nombreEncargado_pro, descripcion_pro, idpersona_con);

        String msg;
        if (nuevo) {
            msg = misDatos.agregarProyectoJefeSubdivision(miProyecto);
            JOptionPane.showMessageDialog(rootPane, msg);
            deshabilitarComposNuevo();
            
          
        }   
        else {
              msg = misDatos.modificarProyectoJefeSubdivision(miProyecto);
            JOptionPane.showMessageDialog(rootPane, msg);
            deshabilitarComposNuevo();
  }

        
    }//GEN-LAST:event_btnGuardarProyectoActionPerformed

    private void btnBuscarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProyectoActionPerformed

         frmBuscarProyectoJefeSubdivision miBusqueda = new frmBuscarProyectoJefeSubdivision(null, closable);
        miBusqueda.setDatos(misDatos);
        miBusqueda.setLocationRelativeTo(null);
        miBusqueda.setVisible(true);
        
        
    }//GEN-LAST:event_btnBuscarProyectoActionPerformed

    private void btnModificarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProyectoActionPerformed

//        nuevo = false;
        permiteModificar();
        
        
    }//GEN-LAST:event_btnModificarProyectoActionPerformed

       public void permiteModificar() {

        try {
            
            String codigo = txtCodigoPro.getText().trim();
            String persona = lblPersona.getText();
            String user = frmPrincipal.usuario;
            String pass = frmPrincipal.clave;
            
           

            String sql = "SELECT codigo_pro, nombre_usu, clave_usu, "
                    + "concat (nombre_gra,' ',nombre_esc,' ',nombre_per,' ',apellido_per) As Persona "
                    + "from usuario "
                    + "inner join persona on persona.idPersona = usuario.idPersona "
                    + "inner join grado on grado.idGrado = persona.idGrado "
                    + "inner join escalafon on escalafon.idEscalafon = persona.idEscalafon "
                    + "inner join proyecto on proyecto.encargado_pro = persona.idpersona "
                    + "where codigo_pro = '" + codigo + "' "
                    + "and nombre_usu = '"+user+"' "
                    + "and clave_usu = '"+pass+"' ";

            ResultSet a = misDatos.getConsulta(sql);
            if (a.next()) {

                String encargado = a.getString("Persona");
                JOptionPane.showMessageDialog(rootPane, "Encargado: " + encargado);

                nuevo = false;
                habilitarCamposModificar();

            } 
            else {

                String password = JOptionPane.showInputDialog(rootPane, "Ingrese Contraseña de Acceso para Modificar el proyecto " + txtNombrePro.getText(), " Ingrese Contraseña", JOptionPane.QUESTION_MESSAGE);
                if (null == password) {

                    return;

                }
                else{
                    
                    String sql2 = "SELECT clave_usu FROM usuario "
                            + "INNER JOIN persona ON persona.idpersona = usuario.idpersona "
                            + "INNER JOIN proyecto ON proyecto.encargado_pro = persona.idpersona "
                            + "WHERE clave_usu = '" + password + "' "
                            + "AND codigo_pro = '" + codigo + "' ";

                    ResultSet b = misDatos.getConsulta(sql2);{
                 
                    if(b.next()){
                        
                        nuevo = false;
                        habilitarCamposModificar();
                        
                    }
                    else{
                        
                         JOptionPane.showMessageDialog(rootPane, "No tiene permisos para modificar el proyecto", "Error", JOptionPane.ERROR_MESSAGE);
                        deshabilitarComposNuevo();
                    }
                    
                }
                    
                    
                }

            }


            
            
            
            
            
           
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(frmJefeSubdivision.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    
    private void txtNombreProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProActionPerformed

    private void txtCodigoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProActionPerformed

    int IDPROYECTO = 0;
    
    public void obteneridproyecto(){
        
        if(txtCodigoPro.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debe Buscar un Proyecto");
        }else {
            try {
            
            
            String sql = "select idProyecto from proyecto where codigo_pro = '"+txtCodigoPro.getText()+"' ";
            ResultSet a = misDatos.getConsulta(sql);
            while (a.next()){
            
                 IDPROYECTO = a.getInt("idProyecto");
                 JOptionPane.showMessageDialog(rootPane, IDPROYECTO);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmJefeSubdivision.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
        
    }
    
      private void habilitarComposNuevo() {
    

          txtNombrePro.setEnabled(true);
          dchFechaInicio.setEnabled(true);
          dchFechaPlazo.setEnabled(true);
          cmbAvance.setEnabled(true);
          cmbEstado.setEnabled(true);
          cmbPrioridad.setEnabled(true);
          cmbMaterialAereo.setEnabled(true);
          cmbEncargado.setEnabled(true);
          txaDescripcion.setEnabled(true);

          btnGuardarProyecto.setEnabled(true);
          btnModificarProyecto.setEnabled(false);

    }
    
      private void habilitarCamposModificar(){
          
          txtNombrePro.setEnabled(true);
          dchFechaInicio.setEnabled(true);
          dchFechaPlazo.setEnabled(true);
          cmbAvance.setEnabled(true);
          cmbEstado.setEnabled(true);
          cmbPrioridad.setEnabled(true);
          cmbMaterialAereo.setEnabled(true);
          cmbEncargado.setEnabled(true);
          txaDescripcion.setEnabled(true);

         
          btnGuardarProyecto.setEnabled(true);
          
          
      }
      
      public static void deshabilitarComposNuevo() {
        
        
        txtNombrePro.setEnabled(false);
          dchFechaInicio.setEnabled(false);
          dchFechaPlazo.setEnabled(false);
          cmbAvance.setEnabled(false);
          cmbEstado.setEnabled(false);
          cmbPrioridad.setEnabled(false);
          cmbMaterialAereo.setEnabled(false);
          cmbEncargado.setEnabled(false);
          txaDescripcion.setEnabled(false);

          
          btnGuardarProyecto.setEnabled(false);
          
    }
    
      
      private void limpiarCampos() {
       
        
        txtNombrePro.setText("");
          dchFechaInicio.setDate(null);
          dchFechaPlazo.setDate(null);
          cmbAvance.setSelectedIndex(0);
          cmbEstado.setSelectedIndex(0);
          cmbPrioridad.setSelectedIndex(0);
          cmbMaterialAereo.setSelectedIndex(0);
          cmbEncargado.setSelectedIndex(0);
          txaDescripcion.setText("");
  
          
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProyecto;
    public static javax.swing.JButton btnGuardarProyecto;
    public static javax.swing.JButton btnModificarProyecto;
    private javax.swing.JButton btnNuevoProyecto;
    public static javax.swing.JComboBox cmbAvance;
    public static javax.swing.JComboBox cmbEncargado;
    public static javax.swing.JComboBox cmbEstado;
    public static javax.swing.JComboBox cmbMaterialAereo;
    public static javax.swing.JComboBox cmbPrioridad;
    public static com.toedter.calendar.JDateChooser dchFechaInicio;
    public static com.toedter.calendar.JDateChooser dchFechaPlazo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPersona;
    public static javax.swing.JTextArea txaDescripcion;
    public static javax.swing.JTextField txtCodigoPro;
    private javax.swing.JLabel txtDescripcion;
    private javax.swing.JLabel txtDescripcion1;
    public static javax.swing.JTextField txtNombrePro;
    // End of variables declaration//GEN-END:variables

    

  
}
