
package Presentacion;


import Negocio.Datos;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author proyectos33
 */
public class frmLogin extends javax.swing.JFrame {

   
    public frmLogin() {
        initComponents();
    }
    
    private Datos misDatos;
      
    
    public void setDatosLogin(Datos misDatos){
    this.misDatos = misDatos;
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso al Sistema");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Usuario:");

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Contraseña:");

        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClaveKeyPressed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1371709169_tick.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAceptarKeyPressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1371709159_cross.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(jButton2))
                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

         //Si el empleado no es valido, muestra mensaje de error 
        if (!misDatos.validarUsuario(txtUsuario.getText(), new String(txtClave.getPassword()))) {
            JOptionPane.showMessageDialog(rootPane, "Usuario o Clave Incorrectos","Error",JOptionPane.ERROR_MESSAGE);
            txtUsuario.setText(""); //Limpiamos JtextField txtUsuario
            txtClave.setText(""); //Limpiamos JtextField txtClave
            txtUsuario.requestFocusInWindow(); //Le damos Foco al JtextField txtUsuario
            return; //Si el ingreso no es valido, rompemos la continuidad de codigo
        }
        frmPrincipal a = new frmPrincipal(); //Creamos el objeto del formulario frmPrincipal
        this.setVisible(false); //Ocultamos formulario Login
        a.setDatosPrincipal(misDatos); //Enviamos los datos
        a.setPerfil(misDatos.getPerfil(txtUsuario.getText())); //Enviamos Perfil
        a.setClave(new String(txtClave.getPassword())); // Enviamos la clave
        a.setUsuario(txtUsuario.getText()); //Enviamos el nombre de usuario
        a.setExtendedState(JFrame.MAXIMIZED_BOTH); //Extendemos el frmPrincipal
        a.setVisible(true); //Hacemos visible el formulario frmPrincipal

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAceptarKeyPressed

//        
//        char caracter = evt.getKeyChar();
//                if(caracter == KeyEvent.VK_ENTER){{
//          //Si el empleado no es valido, muestra mensaje de error 
//        if (!misDatos.validarUsuario(txtUsuario.getText(), new String(txtClave.getPassword()))) {
//            JOptionPane.showMessageDialog(rootPane, "Usuario o Clave Incorrectos","Error",JOptionPane.ERROR_MESSAGE);
//            txtUsuario.setText(""); //Limpiamos JtextField txtUsuario
//            txtClave.setText(""); //Limpiamos JtextField txtClave
//            txtUsuario.requestFocusInWindow(); //Le damos Foco al JtextField txtUsuario
//            return; //Si el ingreso no es valido, rompemos la continuidad de codigo
//        }
//        frmPrincipal miPrincipal = new frmPrincipal(); //Creamos el objeto del formulario frmPrincipal
//        this.setVisible(false); //Ocultamos formulario Login
//        miPrincipal.setDatos(misDatos); //Enviamos los datos
//        miPrincipal.SetPerfil(misDatos.getPerfil(txtUsuario.getText())); //Enviamos Perfil
//        miPrincipal.setClave(new String(txtClave.getPassword())); // Enviamos la clave
//        miPrincipal.setUsuario(txtUsuario.getText()); //Enviamos el nombre de usuario
//        miPrincipal.setExtendedState(JFrame.MAXIMIZED_BOTH); //Extendemos el frmPrincipal
//        miPrincipal.setVisible(true); //Hacemos visible el formulario frmPrincipal
//        }}  
//        
    }//GEN-LAST:event_btnAceptarKeyPressed

    private void txtClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyPressed

           
        char caracter = evt.getKeyChar();
                if(caracter == KeyEvent.VK_ENTER){{
          //Si el empleado no es valido, muestra mensaje de error 
         if (!misDatos.validarUsuario(txtUsuario.getText(), new String(txtClave.getPassword()))) {
            JOptionPane.showMessageDialog(rootPane, "Usuario o Clave Incorrectos","Error",JOptionPane.ERROR_MESSAGE);
            txtUsuario.setText(""); //Limpiamos JtextField txtUsuario
            txtClave.setText(""); //Limpiamos JtextField txtClave
            txtUsuario.requestFocusInWindow(); //Le damos Foco al JtextField txtUsuario
            return; //Si el ingreso no es valido, rompemos la continuidad de codigo
        }
        frmPrincipal a = new frmPrincipal(); //Creamos el objeto del formulario frmPrincipal
        this.setVisible(false); //Ocultamos formulario Login
        a.setDatosPrincipal(misDatos); //Enviamos los datos
        a.setPerfil(misDatos.getPerfil(txtUsuario.getText())); //Enviamos Perfil
        a.setClave(new String(txtClave.getPassword())); // Enviamos la clave
        a.setUsuario(txtUsuario.getText()); //Enviamos el nombre de usuario
        a.setExtendedState(JFrame.MAXIMIZED_BOTH); //Extendemos el frmPrincipal
        a.setVisible(true); //Hacemos visible el formulario frmPrincipal
                }}
        
    }//GEN-LAST:event_txtClaveKeyPressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed

           
        char caracter = evt.getKeyChar();
                if(caracter == KeyEvent.VK_ENTER){{
          //Si el empleado no es valido, muestra mensaje de error 
         if (!misDatos.validarUsuario(txtUsuario.getText(), new String(txtClave.getPassword()))) {
            JOptionPane.showMessageDialog(rootPane, "Usuario o Clave Incorrectos","Error",JOptionPane.ERROR_MESSAGE);
            txtUsuario.setText(""); //Limpiamos JtextField txtUsuario
            txtClave.setText(""); //Limpiamos JtextField txtClave
            txtUsuario.requestFocusInWindow(); //Le damos Foco al JtextField txtUsuario
            return; //Si el ingreso no es valido, rompemos la continuidad de codigo
        }
        frmPrincipal a = new frmPrincipal(); //Creamos el objeto del formulario frmPrincipal
        this.setVisible(false); //Ocultamos formulario Login
        a.setDatosPrincipal(misDatos); //Enviamos los datos
        a.setPerfil(misDatos.getPerfil(txtUsuario.getText())); //Enviamos Perfil
        a.setClave(new String(txtClave.getPassword())); // Enviamos la clave
        a.setUsuario(txtUsuario.getText()); //Enviamos el nombre de usuario
        a.setExtendedState(JFrame.MAXIMIZED_BOTH); //Extendemos el frmPrincipal
        a.setVisible(true); //Hacemos visible el formulario frmPrincipal
                }}
    }//GEN-LAST:event_txtUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
