/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;


import Datos.Usuario;
import Negocio.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cóndor 2013
 */
public class frmUsuario extends javax.swing.JDialog {

    
     private DefaultTableModel miTabla;
      private Datos misDatos;
      private String respuesta = "";
      public static String IBM = "";
      private boolean nuevo = false;
      public static int idpersona = 0;
      String idusuarioTabla = "";
      
      public void setDatosUsu(Datos misDatos) {
        this.misDatos = misDatos;

    }

    public String getRespuesta() {
  return respuesta;

   }
      
    /**
     * Creates new form frmBuscarProyecto
     */
    public frmUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbPerfil = new javax.swing.JComboBox();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblNombrePersona = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Control de Acceso");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Acceso", 0, 0, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Nombre Usuario");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Contraseña:");

        txtNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNombre.setEnabled(false);

        txtClave.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtClave.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Perfil:");

        cmbPerfil.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Perfil", "Administrador", "Jefe Subdivision", "Jefe Modificaciones", "Encargado Proyecto" }));
        cmbPerfil.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbPerfil, 0, 270, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtClave))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblNombrePersona.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombrePersona.setText("Nombre:");

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblTablaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblTabla);

        btnNuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombrePersona)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombrePersona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnGuardar)
                            .addComponent(btnNuevo)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
        private void llenarTabla() {

        String Titulos[] = {"Usuario", "Clave", " perfil","idusuario"};
        String registro[] = new String[4];
        miTabla = new DefaultTableModel(null, Titulos);

       String sql = "SELECT nombre_usu, clave_usu, perfil_usu, idusuario "
               + "FROM usuario "
               + "INNER JOIN persona ON persona.idpersona = usuario.idpersona "
               + "INNER JOIN grado ON grado.idGrado = persona.idGrado "
               + "INNER JOIN escalafon ON escalafon.idEscalafon = persona.idEscalafon "
               + "WHERE ibm_per = '"+IBM+"' ";
        ResultSet rs = misDatos.getConsulta(sql);
        try {
            while (rs.next()) {

                registro[0] = rs.getString("nombre_usu");
                registro[1] = rs.getString("clave_usu");
                registro[2] = rs.getString("perfil_usu");
                registro[3] = rs.getString("idusuario");
                

                miTabla.addRow(registro);
            }
            tblTabla.setModel(miTabla);

        } catch (SQLException ex) {
            Logger.getLogger(frmUsuario.class.getName()).log(Level.SEVERE, null, ex);

        }


    }
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
        mostrarNombrePersona();
        llenarTabla();
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        
        
        
         if (txtNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese Nombre de Usuario", "Error", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocusInWindow();
            
            return;
        }
         
         
                  
         
             if (txtClave.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese Clave para el Usuario", "Error", JOptionPane.ERROR_MESSAGE);
            txtClave.requestFocusInWindow();
            
            return;
        }
             
                if (cmbPerfil.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione Pefil para el Usuario", "Error", JOptionPane.ERROR_MESSAGE);
            cmbPerfil.requestFocusInWindow();
            
            return;
        }
                
                
                
      
        String nombre = txtNombre.getText().trim();
        String clave = txtClave.getText().trim();
        String perfil = cmbPerfil.getSelectedItem().toString();
        int id = idpersona;

        Usuario miUsuario = new Usuario(nombre, clave, perfil, id);

        String msg;
        if (nuevo) {
            
             if (misDatos.existeUsuario(txtNombre.getText())) {
                JOptionPane.showMessageDialog(null, "El Nombre para el usuario Ya Existe", "Error", JOptionPane.ERROR_MESSAGE);
                txtNombre.requestFocusInWindow();
                return;
            }
            
            msg = misDatos.agregarUsuario(miUsuario);
            JOptionPane.showMessageDialog(rootPane, msg);
              btnNuevo.setEnabled(true);
            btnGuardar.setEnabled(false);
            btnModificar.setEnabled(false);
            llenarTabla();

        } else {
            
                        
            msg = misDatos.modificarUsuario(miUsuario);
            JOptionPane.showMessageDialog(rootPane, msg);
            btnNuevo.setEnabled(true);
            btnGuardar.setEnabled(false);
            btnModificar.setEnabled(false);
            llenarTabla();
            
        }
        
        llenarTabla();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        nuevo = true;
        btnGuardar.setEnabled(true);
        txtNombre.setText("");
        txtClave.setText("");
        cmbPerfil.setSelectedIndex(0);
        
        txtNombre.setEnabled(true);
        txtClave.setEnabled(true);
        cmbPerfil.setEnabled(true);
        
        btnModificar.setEnabled(false);
        txtNombre.requestFocusInWindow();
                
        
        
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        nuevo = false;
        
        txtClave.setEnabled(true);
        cmbPerfil.setEnabled(true);
        
        btnGuardar.setEnabled(true);
        btnNuevo.setEnabled(false);
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblTablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaMousePressed

        obtenerFilaUsuario();
        
    }//GEN-LAST:event_tblTablaMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
          eliminarUsuario();
          llenarTabla();
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eliminarUsuario(){
          int row = tblTabla.getSelectedRow();              
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione Fila");
            return;
        }
              
        else  {
            
            misDatos.borrarUsuario(idusuarioTabla);
        llenarTabla();
            
        }
    }
    
    
    
    private void obtenerFilaUsuario(){
        
          int row = tblTabla.getSelectedRow();              
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione Fila");
            return;
        }
              
        else  {
                    
            btnModificar.setEnabled(true);
            btnGuardar.setEnabled(false);
            txtNombre.setEnabled(false);
            txtClave.setEnabled(false);
            cmbPerfil.setEnabled(false);
            txtClave.requestFocusInWindow();
            
            String usuario = tblTabla.getValueAt(row, 0).toString().trim();
            String clave = tblTabla.getValueAt(row, 1).toString().trim();
            String perfil = tblTabla.getValueAt(row, 2).toString().trim();
            String idusuario = tblTabla.getValueAt(row, 3).toString().trim();
            
            
            txtNombre.setText(usuario);
            txtClave.setText(clave);
            cmbPerfil.setSelectedItem(perfil);
            idusuarioTabla = idusuario;
           
            
        }
        
    }
    
    
    
    private void mostrarNombrePersona() {
        
        String sql = "SELECT CONCAT(nombre_gra,' ',nombre_esc,' ',nombre_per,' ',apellido_per) AS 'persona' "
                + "FROM persona "
                + "INNER JOIN grado ON grado.idGrado = persona.idGrado "
                + "INNER JOIN escalafon ON escalafon.idEscalafon = persona.idEscalafon "
                + "WHERE ibm_per = '"+IBM+"'";
        
        ResultSet a = misDatos.getConsulta(sql);
         try {
             while (a.next()){
                 
                 String nombre = a.getString("persona");
                 lblNombrePersona.setText("Nombre: "+nombre);
                 
             }
         } catch (SQLException ex) {
             Logger.getLogger(frmUsuario.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmUsuario dialog = new frmUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cmbPerfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNombrePersona;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    
}
